// <auto-generated />
using System;
using AgendaConsulta.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaConsulta.Api.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20190624011109_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaConsulta.Api.Models.Agenda", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InicioConsulta");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("Date");

                    b.Property<string>("Observacao");

                    b.Property<string>("Paciente")
                        .IsRequired();

                    b.Property<DateTime>("TerminoConsulta");

                    b.HasKey("AgendaId");

                    b.ToTable("Agenda");
                });
#pragma warning restore 612, 618
        }
    }
}
